spring:
  data:
    mongodb:
      database: Productsdb
      host: localhost
      port: 27017
    elasticsearch:
      uris: http://localhost:9200
      username: elastic
      password: KeBZ+Z7*S8jpgCtDLAGy
    main:
      allow-bean-definition-overriding: true